//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInvitation
    {
        public int Id { get; set; }
        public Nullable<long> Userid { get; set; }
        public Nullable<long> DeliveryTypeId { get; set; }
        public Nullable<long> DurationId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> SubscriptionTypeId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsRowActive { get; set; }
        public Nullable<int> PaymentDone { get; set; }
    }
}
